#!/bin/bash
ret=0
if [[ $1 == --clean ]]; then
	yay -Yc --nosave --noprogressbar --noconfirm
else
	deps()
	{
		yay -Syu --needed --noprogressbar --asdeps --noconfirm "$@"
	}
	helpers=$(realpath "${0%/*}/..")
	source ./PKGBUILD
	if ((${#depends[@]} > 0)); then
		printf "%0.s-" {1..80} >&2
		printf "\n::notice file=$PWD/PKGBUILD::RDEP: %s" "${depends[@]}" >&2
	fi
	if ((${#makedepends[@]} > 0)); then
		printf '\n' >&2
		printf "%0.s-" {1..80} >&2
		printf "\n::notice file=$PWD/PKGBUILD::MAKE: %s" "${makedepends[@]}" >&2
	fi
	if ((${#depends[@]} + ${#makedepends[@]} > 0)); then
		printf '\n' >&2
		printf "%0.s-" {1..80} >&2
		printf '\n' >&2
	fi
	((${#depends[@]} == 0)) || deps "${depends[@]}" \
		--makepkg      "$helpers/build" --makepkgconf ~/makepkg.conf
	((ret += $?))
	((${#makedepends[@]} == 0)) || deps "${makedepends[@]}"
	((ret += $?))
fi
exit $ret
