#!/bin/bash
source "${0%/*}/../util.sh"

ret=0
if [[ $1 == --clean ]]; then
	yay -Yc --color always --nosave --noprogressbar --noconfirm
	rm -f ~/.config/yay/config.json
else
	deps()
	{
		yay -Syu --color always --needed --noprogressbar --asdeps --noconfirm "$@"
	}
	helpers=$(realpath "${0%/*}/..")
	source ./PKGBUILD

	cat > ~/.config/yay/config.json << EOF
{
"buildDir": "$(realpath "${0%/*}/../..")/.pkgs/yay/${pkgbase:-$pkgname}"
}
EOF

	if ((${#depends[@]} > 0)); then
		printf "${BOLD}"
		printf "%0.s-" {1..80}
		printf "${ALL_OFF}\n"
		info 'RDEP: %s' "${depends[@]}"
	fi >&2

	if ((${#makedepends[@]} > 0)); then
		printf "${BOLD}"
		printf "%0.s-" {1..80}
		printf "${ALL_OFF}\n"
		info 'MDEP: %s' "${makedepends[@]}"
	fi >&2

	if ((${#depends[@]} + ${#makedepends[@]} > 0)); then
		printf "${BOLD}"
		printf "%0.s-" {1..80}
		printf "${ALL_OFF}\n"
	fi >&2

	((${#depends[@]} == 0)) || deps "${depends[@]}" \
		--makepkg  "$helpers/build" --makepkgconf ~/makepkg.conf
	((ret += $?))
	((${#makedepends[@]} == 0)) || deps "${makedepends[@]}"
	((ret += $?))
fi
exit $ret
