#!/bin/bash
source /etc/makepkg.conf
source ~/makepkg.conf
printf '::notice::Pruning packages\n' >&2

find "$PKGDEST" -maxdepth 1 -type f -name "*$PKGEXT" \
	| sort -u \
	| diff -u - pkgs.txt \
	| grep '^-/' \
	| cut -d- -f2- \
	| awk '{print;print $0".sig";}' \
	| xargs -r rm -fv

repose \
	--arch=x86_64 \
	--root="$PKGDEST" \
	--pool="$PKGDEST" \
	-zvf "$REPO"
