#!/bin/sh
rsync()
{
	map="$1"
	shift
	exec rsync \
		--usermap="$map" \
		--groupmap="$map" \
		--delete \
		-avzh \
		"$@"
}

case "$1" in
	pull)
		rsync "$RUSER:user" "rsync://$RUSER@$RHOST/$RSMOD/" ./.pkgs/repo/
		;;
	push)
		rsync "user:$RUSER" ./.pkgs/repo/ "rsync://$RUSER@$RHOST/$RSMOD/"
		;;
	fetch)
		rsync "$RUSER:user" \
			-m --include="*.sig" --exclude="*" \
			"rsync://$RUSER@$RHOST/$RSMOD/" ./.pkgs/repo/
		;;
esac
