PACKAGE_NAME="vhba-module"
PACKAGE_VERSION="#MODULE_VERSION#"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_CONFIG='!CONFIG_VHBA'

MAKE[0]="make KERNELRELEASE=$kernelver"

BUILT_MODULE_NAME[0]="vhba"
DEST_MODULE_LOCATION[0]="/kernel/drivers/scsi"
