#!/bin/bash
MAINT="${MAINT:-$(getent passwd $USER | cut -d: -f5 | cut -d, -f1 | grep '..*' || echo $USER)}"
REPO=${REPO:-$(dirname "$GITHUB_REPOSITORY")}
EMAIL="${EMAIL:-$USER@$HOSTNAME}"

tar cvf - --files-from /dev/null \
	| gzip -c -f -n > "/pkgs/repo/$REPO.db.tar.gz"
ln -sf "$REPO.db.tar.gz" "/pkgs/repo/$REPO.db"

if [[ -n $GPG_KEY ]]; then
	gpg --import <<< "$GPG_KEY"
	GPGFP="${GPGFP:-$(
		gpg --keyid-format LONG --with-fingerprint --list-secret-keys 2> /dev/null \
			| awk -F = '/Key fingerprint/{print $2;exit}' \
			| tr -d ' '
	)}"
	MAINT="$(
		gpg --with-colons --list-secret-keys "$GPGFP" \
			| awk -F: '/uid/{print $10}'
	)"
	EMAIL=$(
		sed -En 's/^[[:alnum:] ]+ <(.*)>$/\1/p' <<< "$MAINT"
	)
	MAINT=$(
		sed -En 's/^([[:alnum:] ]+) <.*>$/\1/p' <<< "$MAINT"
	)
	printf '%s:6:\n' "$GPGFP" | gpg --import-ownertrust
	cat >> ~/.gnupg/gpg.conf << EOF
default-key 0x$GPGFP
no-emit-version
no-comments
utf8-strings

auto-key-locate clear
auto-key-locate wkd
auto-key-locate local
auto-key-locate keyserver

personal-cipher-preferences AES256 TWOFISH AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256 SHA224
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
EOF
	gpg --armor --export "$EMAIL" > ~/local.gpg
	echo "$GPGFP:4:" > ~/local-trusted
fi

cat > ~/makepkg.conf << EOF
source /etc/makepkg.conf
BUILDENV=(!distcc color !ccache check sign)
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug !lto)

PACKAGER="$MAINT <$EMAIL>"
GPGKEY="$GPGFP"
BUILDDIR=/pkgs/build
PKGDEST=/pkgs/repo
LOGDEST=/pkgs/logs

PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'
EOF

#yay -Syu --asexplicit --noprogressbar --noconfirm base-devel
