#!/bin/bash

BASEDIR="$(dirname "$(realpath "$0")")"

[[ -d $BASEDIR/aurpublish-master ]] || (
	trap 'rm -f "$BASEDIR/master.tgz"' INT TERM EXIT
	curl -L#o "$BASEDIR/master.tgz" \
		https://github.com/eli-schwartz/aurpublish/archive/refs/heads/master.tar.gz
	tar -C "$BASEDIR" -xaf "$BASEDIR/master.tgz"
)

[[ -x $BASEDIR/aurpublish-master/aurpublish ]] || (
	exec < "$BASEDIR/aurpublish-master/aurpublish.in"
	exec > "$BASEDIR/aurpublish-master/aurpublish"
	set -e
	sed -e "s|@HOOKSDIR@|$BASEDIR/aurpublish-master|g"
	chmod +x "$BASEDIR/aurpublish-master/aurpublish"
)

exec -a aurpublish "$BASEDIR/aurpublish-master/aurpublish" "$@"
