#!/bin/bash
source "${0%/*}/util.sh"
shopt -s nullglob
shopt -s extglob

base=$(realpath "${0%/*}/..")

pkgbase="$(basename "$PWD")"
sha()
{
	sha256sum "$1" | awk '{print $1}'
}
NOBUILD=0
NOBUILDOPTS=$(
	grep BUILDPKG=0 /usr/bin/makepkg \
		| cut -d\) -f1 \
		| awk '{print $1}' \
		| tr '|' '\n'
)

NOBUILDOPTS="--($(
	awk -F - '/^--/{printf $3"|"}' <<< "$NOBUILDOPTS" \
		| sed 's/|$/\n/'
))|-[^-]*($(
	awk -F - '/^-/ && ! /^--/ {printf $2"|"}' <<< "$NOBUILDOPTS" \
		| sed 's/|$/\n/'
)).*"

if [[ -d "$base/$pkgbase" && "$PWD" != "$base/$pkgbase" && ! -f .rsynced ]]; then
	rsync --stderr=all -aqz "$base/$pkgbase/" . >&2
	touch .rsynced
fi

if ! grep -q -- '--config '"$HOME"'/makepkg.conf' <<< "$*"; then
	set -- --config ~/makepkg.conf "$@"
fi

export SRCDEST="$base/.pkgs/src/$pkgbase"

if printf '%s\n' "$@" \
	| grep -qE -- '^('"$NOBUILDOPTS"')$'; then
	NOBUILD=1
fi

# Override pkgrel
if ((NOBUILD == 0)) \
	|| (printf '%s\n' "$@" \
		| grep -qE -- '^--packagelist$'); then
	"${0%/*}/maint/pkgrel"
fi

if ((NOBUILD)); then
	"${0%/*}/maint/pkgs"
	exec makepkg "$@"
fi

# Build package
dbug 'Building pkgbase: %s' "$pkgbase"
makepkg --nocheck "$@"
ret=$?

if [[ -f .rsynced ]]; then
	rm .rsynced
fi

# Update meta info
if ((ret == 0 || ret == 13)); then
	if ((ret == 13)); then
		ret=0
	fi
	"${0%/*}/maint/pkgs"
	((ret += $?))
else
	fail 'file=%s' 'Failed to build: %s' "$PWD/PKGBUILD" "$pkgbase"
fi

exit $ret
