#!/bin/bash -e
shopt -s nullglob
shopt -s extglob

built=()
base=$(realpath "${0%/*}/..")
helpers="$base/.helpers"

cd "$base" || exit 1

truncate -s 0 pkgs.txt ipc

for each in */; do
	unset pkgs pkgbase
	truncate -s 0 ipc

	pkgbase=$(basename "$each")
	[[ -f $pkgbase/PKGBUILD ]] || continue
	if grep -q "$pkgbase" buildignore; then
		printf '::notice file=buildignore::Skip building %s\n' "$pkgbase" >&2
		continue
	else
		printf '::group::Build %s\n' "$pkgbase" >&2
	fi
	pushd "$pkgbase" || {
		printf '::error:: file=%s,line=25::Failed to change directory: %s' "$0" "$pkgbase" >&2
		printf '::endgroup::\n' >&2
		continue
	}

	if
		"$helpers/maint/deps" \
			&&
			# Get dependencies
			"$helpers/build" # Build package
	then
		readarray -t pkgs < "$base/ipc"
		built+=("${pkgs[@]}")
		printf '::debug::Built package: %s\n' "${pkgs[@]}" >&2
	else
		printf '::error:: file=%s,line=33::Failed to build: %s\n' "$0" "$pkgbase" >&2
	fi
	"$helpers/maint/deps" --clean
	popd || :
	printf '::endgroup::\n' >&2
done

# TODO: prune
