#!/bin/bash -e
shopt -s nullglob
shopt -s extglob

built=()
base=$(realpath "${0%/*}/..")
helpers="$base/.helpers"

source "$helpers/util.sh"

cd "$base" || exit 1

truncate -s 0 pkgs.txt ipc
if [[ $# -eq 0 ]]; then
	set -- */
fi

for each in "$@"; do
	unset pkgs pkgbase
	truncate -s 0 ipc

	pkgbase=$(basename "$each")
	[[ -f $pkgbase/PKGBUILD ]] || continue
	if grep -xqF "$pkgbase" "$base/buildignore"; then
		warn 'file=buildignore' 'Skip building %s' "$pkgbase"
		continue
	else
		printf "::group::${GREEN}${BOLD}Build %s${ALL_OFF}\n" "$pkgbase"
	fi
	pushd "$pkgbase" || {
		fail 'file=%s,line=25' 'Failed to change directory: %s' "$0" "$pkgbase"
		printf '::endgroup::\n' >&2
		continue
	}

	if "$helpers/maint/deps"; then # Get dependencies
		if "$helpers/build"; then # Build package
			readarray -t pkgs < "$base/ipc"
			built+=("${pkgs[@]}")
			dbug 'Built package: %s' "${pkgs[@]}"
		fi
	else
		fail 'file=%s,line=32' 'Failed to install dependencies of: %s' "$0" "$pkgbase"
	fi
	"$helpers/maint/deps" --clean
	popd || :
	printf '::endgroup::\n'
done

# Sort the prune whitelist
(
	set -e
	cut -d: -f2- "$base/pkgs.txt" \
		| sort -u > "$base/txt.pkgs"
) && mv "$base/txt.pkgs" "$base/pkgs.txt"
