name: makepkg

on:
  # Allow manual start
  workflow_dispatch:
  # Run job on 00:00UTC daily
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group:  ${{ github.workflow }}-${{ github.ref }}
    environment: buildpkg
    container:
      image: ghcr.io/greyltc/archlinux:latest
      options: -u root
    steps:
    - name: Install workflow dependencies
      run: pacman -Sy nodejs patch git --overwrite="*" --noprogressbar --noconfirm --needed

    - name: Mark workdir as safe
      run: git config --global --add safe.directory $PWD

    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Prepare build user
      run: . ./.helpers/init/useradd

    - name: Prepare build environment
      run: su user -c ./.helpers/init/prepare-docker
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        REPO:    ahm-aur

    - name: Prepare pacman-keyrings
      run: . ./.helpers/init/keyring

    - name: Add local mirrors
      if: ${{ env.ACT }}
      run: . ./.helpers/act/mirrorlist

    - name: Update pacman-mirrors
      run: . ./.helpers/init/mirrorlist

    - name: Update build environment
      run: . ./.helpers/init/pacman-syu

    - name: Fetch package signatures
      run: ./.helpers/maint/rsync fetch
      env:
        RUSER: ${{ secrets.REPO_USER }}
        RHOST: ${{ secrets.REPO_HOST }}
        RSMOD: pacman
        RSYNC_PASSWORD: ${{ secrets.REPO_PASS }}

    - name: Init cache
      if: ${{ !env.ACT }}
      uses: actions/cache@v4
      with:
        key: makepkg-${{ hashFiles('./.pkgs/repo/*.sig') }}
        path: ./.pkgs/repo
        restore-keys: makepkg-

    - name: Pull remote
      run: ./.helpers/maint/rsync pull
      env:
        RUSER: ${{ secrets.REPO_USER }}
        RHOST: ${{ secrets.REPO_HOST }}
        RSMOD: pacman
        RSYNC_PASSWORD: ${{ secrets.REPO_PASS }}

    - name: Build packages
      run: su user -c ./.helpers/build-all

    - name: Prune packages
      run: su user -c ./.helpers/maint/prune-pkg
      env:
        REPO: ahm-aur

    - name: Push remote
      run: ./.helpers/maint/rsync push
      env:
        RUSER: ${{ secrets.REPO_USER }}
        RHOST: ${{ secrets.REPO_HOST }}
        RSMOD: pacman
        RSYNC_PASSWORD: ${{ secrets.REPO_PASS }}

    - name: Upload logs
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: log
        path: ./.pkgs/logs
        if-no-files-found: warn
        retention-days: 4
# vim: ft=yaml:ts=2:et:
